### ISSUE TITLE
dz rewiev lessons 4

### ISSUE THREAD

**Issue by andrewmarushko** [Jeka-vn/Jeka-vn.github.io#2]
# Не зачет

нужно поправить менюшку сильно она какая-то у тебя тонкая добавь падингов побольше и так же с текстом в колонках и главном контенте

**Comment by Jeka-vn** [comment]
Добавил падинги)

**Comment by andrewmarushko** [comment]
А как насчет DropDown?

**Comment by Jeka-vn** [comment]
Я все поправил. Можите еще раз посмотреть пажалуйста?

**Comment by andrewmarushko** [comment]
Ничего не  )

**Comment by Jeka-vn** [comment]
Да вроде все). что именно я забыл?)

**Comment by andrewmarushko** [comment]
НУ как бы ничего не поменялось )

**Comment by andrewmarushko** [comment]
# Done!
