### ISSUE TITLE
DZ Rewiev lessons 5

### ISSUE THREAD

**Issue by andrewmarushko** [Jeka-vn/Jeka-vn.github.io#3]
# НЕ зачет
### Начинаем писать чисто и качественно! )

1) в инспекторе у тебя уже 3 ошибки с css token

<img width="1280" alt="screenshot 2015-11-10 15 56 30" src="https://cloud.githubusercontent.com/assets/4026421/11064268/c6ff812a-87c4-11e5-8ed5-25a914b4cb99.png">
<img width="814" alt="screenshot 2015-11-10 15 56 14" src="https://cloud.githubusercontent.com/assets/4026421/11064266/c6d00bac-87c4-11e5-88f2-9eaa40bb283a.png">

2) для боди ставить фоновую картинку не желательно, если у тебя будет контент добавляться к примеру еще форма будет - шлак
и вот такую штуку пишем все только в одном свойстве "background"

<img width="238" alt="screenshot 2015-11-10 16 12 24" src="https://cloud.githubusercontent.com/assets/4026421/11064470/12329c58-87c6-11e5-99de-d51bdfd8eb46.png">

3) Это вообще кто тебя так учил делать???

<img width="314" alt="screenshot 2015-11-10 16 21 28" src="https://cloud.githubusercontent.com/assets/4026421/11064645/28332efe-87c7-11e5-81ca-4cec302b0106.png">
Переделать!

4) Это что то мне вообще не нравиться предаставь что будет при адаптивной верстке в будущем все равно прийдется переделать

.form{
<img width="214" alt="screenshot 2015-11-10 16 29 57" src="https://cloud.githubusercontent.com/assets/4026421/11064851/70c57464-87c8-11e5-9eda-e9dfec9262c0.png">
}

5) нужно всегда ставить паддинг с права что бы введенный текст не прилипал к краю инпута

<img width="79" alt="screenshot 2015-11-10 16 34 59" src="https://cloud.githubusercontent.com/assets/4026421/11064949/29652b90-87c9-11e5-93d8-6b3fa6fb2f4c.png">

6) для чего инпуты, чекбокс и батн выносить в разные формы 0о?? --- __почитай как работает форма для общего развития и полного понимания!!!__
<img width="361" alt="screenshot 2015-11-10 16 44 44" src="https://cloud.githubusercontent.com/assets/4026421/11065180/8ab0f5b8-87ca-11e5-86fa-96425fc82408.png">

**Comment by Jeka-vn** [comment]
Поправил.

**Comment by andrewmarushko** [comment]
@Jeka-vn 

# DONE!
