### ISSUE TITLE
dz rewiev lessons 6

### ISSUE THREAD

**Issue by andrewmarushko** [Jeka-vn/Jeka-vn.github.io#4]
# НЕ зачет
- [x]  поправить кнопки входа и регистрации, поиска по фильтрам

<img width="105" alt="screenshot 2015-11-14 15 05 11" src="https://cloud.githubusercontent.com/assets/4026421/11163681/376abee2-8ae1-11e5-8503-b69cd1d74e13.png">

<img width="128" alt="screenshot 2015-11-14 14 43 44" src="https://cloud.githubusercontent.com/assets/4026421/11163606/74921502-8ade-11e5-8f42-6c839209686c.png">
- [x] это никуда не годиться каждый бренд должен быть ссылкой со своим логотипом

<img width="371" alt="screenshot 2015-11-14 15 13 29" src="https://cloud.githubusercontent.com/assets/4026421/11163721/5ad58032-8ae2-11e5-9d61-604477890baa.png">
- [x] | - нужно сделать бордером, а не span

<img width="254" alt="screenshot 2015-11-14 15 18 24" src="https://cloud.githubusercontent.com/assets/4026421/11163756/a3a9d7b2-8ae3-11e5-9083-43e75d30ca17.png">

**Comment by Jeka-vn** [comment]
Проверь пажалуйста. Вроде поправил.)
